# Generated by Django 5.1.3 on 2024-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_otp_account_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
