# Generated by Django 5.1.3 on 2024-11-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_email_verified_alter_account_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
