# Generated by Django 5.1.3 on 2024-12-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendor_user'),
        ('orders', '0002_alter_order_vendor_orderitem_delete_vendorreview'),
        ('products', '0004_alter_product_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
