# Generated by Django 5.1.3 on 2024-12-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Tools', 'Tools'), ('Furniture', 'Furniture'), ('Phone', 'Phone'), ('Accessories', 'Accessories'), ('Home Appliances', 'Home Appliances'), ('Laptop', 'Laptop'), ('Computer Accessories', 'Computer Accessories'), ('Camera', 'Camera'), ('Gadgets', 'Gadgets'), ('Watches', 'Watches'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Jewelry', 'Jewelry'), ('Baby Products', 'Baby Products'), ('Beauty', 'Beauty'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Foods', 'Foods'), ('OTHERS', 'Others')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default='product_images/default-product-image.png', null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor')),
            ],
        ),
    ]
