# Generated by Django 5.1.3 on 2024-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Tools', 'Tools'), ('Furniture', 'Furniture'), ('Phone', 'Phone'), ('Accessories', 'Accessories'), ('Home Appliances', 'Home Appliances'), ('Laptop', 'Laptop'), ('Computer Accessories', 'Computer Accessories'), ('Camera', 'Camera'), ('Gadgets', 'Gadgets'), ('Watches', 'Watches'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Jewelry', 'Jewelry'), ('Baby Products', 'Baby Products'), ('Beauty', 'Beauty'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Foods', 'Foods'), ('OTHERS', 'Others')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
